<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Meta Conversions API sender.
 *
 * Called by the outbox drainer for rows whose destination is 'meta_capi'.
 * Builds and posts a CRM stage event to the brand's dataset.
 *
 * Design decisions that come straight from Meta's payload spec, and are easy to
 * get silently wrong:
 *   - action_source is "system_generated" for CRM stage events. There is no
 *     "offline" value; using it fails quietly. It is never "business_messaging"
 *     here either: these events are generated by the CRM, not inside a live
 *     messaging thread, even for leads that came from click-to-WhatsApp.
 *   - For a lead that came from Lead Ads, the primary key is the Meta lead_id,
 *     NOT hashed email/phone. Hashed identifiers are added as redundancy.
 *   - custom_data.event_source must be "crm"; lead_event_source names the tool.
 *   - event_name is the pipeline stage verbatim; Meta learns per name, so it
 *     must be stable and treatment-agnostic.
 *   - No clinical field (procedure, diagnosis, body area, photo, any health
 *     attribute) is ever placed in the payload.
 *
 * This function is GATED: it only sends when the brand has a dataset id and a
 * system-user token. Without a token (the state until Meta App Review completes)
 * it returns a clear, non-fatal reason so the row is held, not lost.
 */
function se_capi_send_event($row)
{
    $CI = &get_instance();

    $brand_id = (int) $row['brand_id'];
    $lead_id  = (int) $row['lead_id'];

    $CI->db->where('id', $brand_id);
    $brand = $CI->db->get(db_prefix() . 'se_brands')->row();

    if (!$brand || empty($brand->meta_dataset_id)) {
        return ['ok' => false, 'error' => 'brand has no meta_dataset_id',
                'class' => SE_OUTBOX_FAIL_GATED, 'code' => 'no_dataset'];
    }

    // Dataset-drift guard: refuse to transmit when the brand's dataset id does
    // not match the recorded authoritative id for this brand. Sending web
    // conversions to the wrong dataset (e.g. the WhatsApp MM dataset) corrupts
    // optimisation and attribution, so block loudly and hold — the row is not
    // lost, and the error names the correct id to restore.
    if (function_exists('se_capi_dataset_conflict')) {
        $expected = se_capi_dataset_conflict($brand_id);
        if ($expected !== null) {
            return ['ok' => false,
                    'error' => 'dataset id conflict: brand is set to ' . $brand->meta_dataset_id
                             . ' but the authoritative dataset for this brand is ' . $expected
                             . ' — transmission blocked until reconciled',
                    'class' => SE_OUTBOX_FAIL_GATED, 'code' => 'dataset_conflict'];
        }
    }

    if (function_exists('se_capi_enabled') && !se_capi_enabled($brand_id)) {
        return ['ok' => false, 'error' => 'meta capi disabled for brand',
                'class' => SE_OUTBOX_FAIL_GATED, 'code' => 'disabled'];
    }

    // The system-user token is a secret: it lives in the FILE secret store
    // (meta_capi_<brand>), the same source se_capi_ready()/health check, so a
    // "ready" CAPI leg truthfully implies this send has a token. Legacy option
    // storage is honoured last for back-compat. Never in the brands table that
    // renders in the UI, and never in git.
    $token = function_exists('se_meta_capi_token')
        ? se_meta_capi_token($brand_id)
        : (get_option('se_meta_capi_token_' . $brand_id) ?: get_option('se_meta_capi_token'));

    if (empty($token)) {
        // An external gate is not a delivery failure: hold without consuming
        // an attempt, so the queue survives however long App Review takes.
        return ['ok' => false, 'error' => 'no Meta system-user token configured (App Review pending)',
                'class' => SE_OUTBOX_FAIL_GATED, 'code' => 'no_token'];
    }

    /* A row without a snapshot is unsendable: we cannot prove what the consent
     * or identifiers were when the event happened, and rebuilding them from the
     * lead's current row is the defect the snapshot exists to remove. */
    if (!se_outbox_row_has_snapshot($row)) {
        return ['ok' => false, 'error' => 'no event snapshot; refusing to rebuild from the live lead',
                'class' => SE_OUTBOX_FAIL_PERMANENT, 'code' => 'no_snapshot'];
    }

    $lead = null;

    $CI->load->library('se_core/se_hash');

    $event = se_capi_build_event($row, $lead);

    if (empty($event['user_data'])) {
        return ['ok' => false, 'error' => 'no usable identifiers on lead',
                'class' => SE_OUTBOX_FAIL_PERMANENT, 'code' => 'no_identifiers'];
    }

    $payload = ['data' => [$event]];

    $version = get_option('se_meta_graph_version') ?: 'v26.0';

    // The token goes in the Authorization header, NOT the query string: a URL
    // is logged by proxies, appears in error text and lands in access logs.
    $url = 'https://graph.facebook.com/' . $version . '/'
         . rawurlencode($brand->meta_dataset_id) . '/events';

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => json_encode($payload),
        CURLOPT_HTTPHEADER     => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $token,
        ],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 30,
    ]);

    $body = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $cerr = curl_error($ch);
    curl_close($ch);

    if ($cerr) {
        return ['ok' => false, 'error' => 'transport error',
                'class' => SE_OUTBOX_FAIL_RETRYABLE, 'code' => 'curl'];
    }

    if ($code >= 200 && $code < 300) {
        return ['ok' => true, 'error' => '', 'class' => null, 'code' => 'ok'];
    }

    // 4xx is our problem and will not fix itself; 401/403/429 and 5xx will.
    $class = ($code >= 400 && $code < 500 && !in_array($code, [401, 403, 408, 429], true))
        ? SE_OUTBOX_FAIL_PERMANENT
        : SE_OUTBOX_FAIL_RETRYABLE;

    return ['ok' => false, 'error' => 'HTTP ' . $code, 'class' => $class, 'code' => 'http_' . $code];
}

/**
 * Build the Conversions API event array for a lead + outbox row.
 *
 * Pure and network-free (no DB, no curl) so it can be unit-tested directly.
 * The caller must have loaded the Se_hash library first.
 *
 * Invariants enforced here and covered by the payload tests:
 *   - action_source is ALWAYS 'system_generated' for CRM/appointment events.
 *   - custom_data carries only event_source='crm' and lead_event_source; it must
 *     NEVER contain procedure, diagnosis, body area, photo or any health field.
 *   - Lead-Ads lead_id is the preferred identifier, emitted as a string.
 *   - email/phone are Turkish-safe normalised then SHA-256 hashed; ctwa_clid is
 *     emitted UNHASHED per Meta's spec.
 */
function se_capi_build_event($row, $lead = null)
{
    $user_data = [];

    if (se_outbox_row_has_snapshot($row)) {
        /* --- snapshot path: what was true when the conversion happened --- */
        $snap = se_outbox_snapshot_decode($row['attribution_snapshot']);
        $ft   = $snap['first_touch'] ?? [];
        $ids  = $snap['identifiers'] ?? [];
        $dest = $snap['destination'] ?? [];

        if (!empty($dest['meta_lead_id'])) {
            $user_data['lead_id'] = (string) $dest['meta_lead_id'];
        }
        if (!empty($ids['em'])) {
            $user_data['em'] = [(string) $ids['em']];   // already SHA-256
        }
        if (!empty($ids['ph'])) {
            $user_data['ph'] = [(string) $ids['ph']];
        }
        foreach (['ctwa_clid', 'fbc', 'fbp'] as $raw) {
            if (!empty($ft[$raw])) {
                $user_data[$raw] = (string) $ft[$raw];
            }
        }
    } elseif ($lead) {
        /* --- pre-snapshot rows keep the original live-lead behaviour ----- */
        if (!empty($lead->meta_lead_id)) {
            $user_data['lead_id'] = (string) $lead->meta_lead_id;
        }
        if (!empty($lead->email) && ($em = Se_hash::email($lead->email))) {
            $user_data['em'] = [Se_hash::sha256($em)];
        }
        if (!empty($lead->phonenumber) && ($ph = Se_hash::phone($lead->phonenumber))) {
            $user_data['ph'] = [Se_hash::sha256($ph)];
        }
        if (!empty($lead->ctwa_clid)) {
            $user_data['ctwa_clid'] = (string) $lead->ctwa_clid;
        }
        if (!empty($lead->fbc)) {
            $user_data['fbc'] = (string) $lead->fbc;
        }
        if (!empty($lead->fbp)) {
            $user_data['fbp'] = (string) $lead->fbp;
        }
    }

    // These are CRM/appointment conversions fired by our own system, not messages
    // inside a live thread, so action_source is ALWAYS 'system_generated' (even for
    // leads that originated from click-to-WhatsApp; ctwa_clid is still sent above as
    // an attribution identifier and does not change where THIS event occurs).
    $action_source = 'system_generated';

    return [
        'event_name'    => $row['event_name'],
        'event_time'    => strtotime($row['event_time']),
        'action_source' => $action_source,
        'user_data'     => $user_data,
        'custom_data'   => [
            'event_source'      => 'crm',
            // Names the CRM to Meta. The clinic name since clinic mode (se_clinic.php).
            'lead_event_source' => defined('SE_CLINIC_NAME') ? SE_CLINIC_NAME : 'SEO Evaluate CRM',
        ],
        'event_id'      => 'se-' . (int) $row['lead_id'] . '-' . $row['id'],
    ];
}
